### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by binary1230**
bump this to match current ubersystem version

### CODE REVIEW

**Comment by binary1230** [comment]
I'm having an issue running 'sep' on staging servers, it's saying:

```python
Traceback (most recent call last):
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 645, in _build_master
    ws.require(__requires__)
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 946, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 838, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (pytest 2.7.2 (/usr/local/uber/env/lib/python3.4/site-packages), Requirement.parse('pytest==2.5.2'), {'sideboard'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./sep", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3074, in <module>
    @_call_aside
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3060, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 3087, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 647, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 660, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/uber/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 833, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pytest==2.5.2' distribution was not found and is required by sideboard
```

But.... weirdly enough this only happens on current deploys and not on my new deploy changes, which suggest to me that maybe the sideboard dependencies aren't being installed on current prod/staging servers, which would be bad.

I'll investigate some more.  Meantime, maybe we should just bump this anyway?

**Comment by EliAndrewC** [comment]
Ha, good catch.  I'd already bumped this in my local Sideboard's ``requirements.txt`` and had been intending to make this PR myself, but then it just slipped my mind.  That must be why I don't see this issue on my local dev box.  I'll wait for travis to pass and then merge this.  Thanks!

**Comment by binary1230** [comment]
Hm, confirmed that on my new deploy server, stage3, sep isn't complaining there at all.

I wonder if this is puppet not picking up the dependency change when it was added a few days ago to requirements.txt.

**Comment by binary1230** [comment]
at any rate, the new version of the puppet deploy stuff should be much more targeted about when it runs 'paver install_deps', anytime there are new commits being pulled down, it'll run that.  I say we bump this and then yea just see if it comes back up again.

**Comment by binary1230** [comment]
thx for the merge

**Comment by binary1230** [comment]
at any rate doing this and running 'sep print_config' works again.  weirdness.

**Pull request merged**
