### PR TITLE
Add Dockerfile from upstream

### PR DESCRIPTION
**Pull request by kitsuta**
Upstream needs to sync up with MAGFest's sideboard. Even if this isn't merged, we need it to create a mergeable PR.

### CODE REVIEW

**Comment by RobRuana** [comment]
I am cool with this. @EliAndrewC looks good?

**Comment by EliAndrewC** [comment]
LGTM although I don't speak Docker.  Still, people who don't care about Docker can just ignore this file, so it's not going to hurt anything to include it in the repo.

**Comment by kitsuta** [comment]
The failing unit tests seem unrelated, but should we be concerned about them?

**Comment by binary1230** [comment]
+1

On May 4, 2017 10:09 AM, "Victoria Earl" <notifications@github.com> wrote:

Merged #79 <https://github.com/magfest/sideboard/pull/79>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/magfest/sideboard/pull/79#event-1068990793>, or mute
the thread

**Pull request merged**
